stages:
    - build

maven-build-stage:
    image: maven:3.8.7-eclipse-temurin-8-alpine
    stage: build
    script: mvn clean package
    artifacts:
        paths: 
            - target/boot-demo-0.0.1-SNAPSHOT.jar